# Follow Your Passion?

In The Scout Mindset by Julia Galef, the author tells this story about herself:

> When I was sixteen, I seriously considered moving to New York after my high school graduation to pursue a career on the stage. I knew the odds would not be in my favour. Acting is a notoriously difficult way to make a living; stage acting even more so. But I had been bitten by the theatre bug, and spent my evenings singing along to my *Rent* and *Les Misérables* soundtracks on CD while daydreaming about being on Broadway.
> I happened to know a successful stage actor, so I asked him what he thought I should do, given the long odds. "Screw the odds," he told me. "Everything in life is a risk, but if you want it, you should go for it. If you worry about failing, that's just going to be a self-fulfilling prophecy."

(salutation)

Where have you heard stories like this one before? Perhaps, in just about every speech like this one. Galef calls this the "self-belief model of success": once you've convinced yourself that you'll succeed, you'll have the motivation to try hard things and persist when it gets difficult. You have to get the possibility of failure out of your mind, or it will discourage you from continuing.

I am here to tell you that this is *complete nonsense*. This is not at all how it works.

Galef, in her book, talks about the Soldier Mindset and the Scout Mindset. 

The Soldier Mindset defends beliefs as if they are military positions; arguments are either attacks on or defences of this position. Changing your mind is like surrender. The point of reasoning is to strengthen beliefs that the Soldier already holds. Such people grab hold of evidence that supports their beliefs and ignore completely any evidence that doesn't. This is called "motivated reasoning", and we all do it to some extent. What kind of stories do you share on Facebook or other social media? Are they ones that confirm what you already think?

The Scout Mindset takes a very different approach. In military terms, a Scout is someone who looks carefully at the landscape through binoculars, trying to find out where the enemy is, what the terrain is like, what manoeuvres might be possible. The Scout is asking the question "what is really there?":  using the evidence that they can gather to build a picture of what is true, regardless of what that truth might look like. A Scout is not afraid of changing their mind when new evidence comes in; it merely means that they have come closer to the truth.

So, let us return to Galef's passion for acting. She did some research:

> Out of the 49,000 members in Actor's Equity, only 17,000 get any work at all in a given year. Of those who do get work, the median annual salary is $7,500. ... Of course, any individual may have a better or worse chance of success than the overall odds suggest, based on how talented, hardworking, charismatic, or well-connected they are. But the overall odds are an important baseline to be aware of.

Galef talked to a second actor, who said that it was really tough, and to consider whether Galef had other careers that she could be excited about.

Here is the thing: most of us may think that we have only one passion, but in actual fact there are often several different things that are, or could become, passions, or different ways to put a passion to use. I'm a teacher; I happen to have gotten lucky enough to teach at UTSC, but if that hadn't worked out, I might have been as successful in corporate training, for example. 

Here is why the self-belief approach doesn't work: by focusing single-mindedly on your passion and not allowing yourself to have negative thoughts, you shut yourself off from any analysis of the risks involved, and in particular whether the risk involved is worth the reward if successful. Or, there might be different ways to be equally successful that have less risk attached. 

How does this relate to Soldier Mindset and Scout Mindset? Well, the self-belief approach requires you to believe you'll succeed and put any thoughts of failure out of your mind. This stops you from making a proper assessment of risk vs reward: in other words, you are showing Soldier Mindset. Being open to the possibility of different passions with different risks and rewards is asking "what is really there": it is a Scout mindset.

So now you're thinking, "well, once I've chosen my passion, don't I need to devote myself single-mindedly to it, and ignore the possibility of failure?"

Let me tell you about Elon Musk. He is very much in the news recently after his purchase of Twitter. One of his earlier companies was PayPal, which he sold for $180 million. He bet most of that money on the company that would become SpaceX. They warned him "you're going to fail. You'll lose all your PayPal money". You've heard stories like this that go on "but he wouldn't be deterred, because he knew in his heart that the doubters were wrong", and you're thinking that Musk is just the same here. But no: he replied to his friends "well, I agree. I think we probably will fail." What was Musk thinking? We are used to doing things because they are likely to succeed, but that's only part of the story: the right reason for doing something is when the reward is high enough relative to the risk. Musk thought that the possibility of making space travel viable was a huge reward, and was willing to accept only a small chance of success for the chance of reaping that reward.

The point of all of this is that the chance of success changes all the time depending on things that happen, and having a Soldier Mindset blinds you to this. Having instead a Scout mindset means that you have an up to date assessment of the current risk and reward, and you know where you stand. For example, you might decide to change your plans for a greater chance at a lesser reward. 

Acting like a Soldier can be effective in the short term, but it is brittle: you need to avoid or rationalize away information that will stop you believing in success. Acting like a Scout, on the other hand, is being motivated by the knowledge that you are making a smart bet, one that you can feel good about whether it succeeds or not. Not every bet will win, but if you make enough good ones, you will succeed often enough.

Following your passion is a fine thing to do, as long as it is a passion for which the reward justifies the risk. That means being open to what the risks are and to how they develop over time: that is, to being not a Soldier but a Scout.



